### ISSUE TITLE
InvalidKeyPair.NotFound

### ISSUE THREAD

**Issue by melshman** [scottslowe/2018-itx-iac-workshop#3]
Scott,
What are some of the most common issues with entering the key_pair value when editing the terraform.tfvar file?  I am hitting a road block.  First I had a hard time getting it to accept the value I got from my 'MyAWSKeyPair.pem' RSA PRIVATE KEY that was provided by AWS for my laptop to connect to my instances via SSH???  This was because it was multi-line with new line issues.  

Am I using the correct value?  Or am I completely off basis here.  I was not in the class at interop but wanted to be, so I am doing these labs without knowledge of any tips you might have provided in class.  

Once I got the value to be accepted when I ran the 'terraform plan' command, I get errors related to my key pair:  aws_instance.instance.1: 
Error launching source instance: InvalidKeyPair.NotFound: The key pair 'MIIE.......really long multi-line key......xxx' does not exist status code:  400.

THANKS!!!!

**Comment by scottslowe** [comment]
@melshman The key_pair value needs to point to the name of an existing AWS key pair. If you log into your AWS console, navigate to the EC2 service, and then select Key Pairs from the menu on the left, you'll see which key pairs AWS knows about.

Let me know if this helps at all.

**Comment by melshman** [comment]
@scottslowe  That worked!  Awesome.  This is fun 👍

**Comment by melshman** [comment]
Yep.  that did the trick. Appreciate the quick response.

BTW... is my use of 'issues' on Github an acceptable place to ask such
questions related to a issues using a repository?  Or is it restricted
within the community to be more related to code defects, etc.?  I want to
make sure I am using the system correctly.

Thanks,
Tim

**Comment by scottslowe** [comment]
@melshman This is a perfectly valid way to ask questions about the repository's content. Some other repositories may prefer that you use issues only as a means of reporting a code defect, but for me I have no such restrictions or requirements. Thanks!

Closing this issue now that the problem has been addressed. Please feel free to re-open as needed.
