### ISSUE TITLE
Ansible... and then AWS Provider

### ISSUE THREAD

**Issue by melshman** [scottslowe/2018-itx-iac-workshop#4]
Scott,
Everything I did in labs 01 and 02 were using windows 10.  When I got to lab 3 and tried to get ansible installed, I realized that I needed to be on Linux or Mac.  I choose to use WSL running Ubuntu on my windows machine.  Is this ok?
Initially I thought that I would just run Ansible on Ubuntu, and leave the Terraform on my windows machine, but run into issues and abandon that quickly.  I get the following error:  
$ python ec2.py
**region name: None likely not supported, or AWS is down.  connection to region failed.**

instead of TSHOOT the above, I then installed Git, Terraform, and Ansible on my WSL Ubuntu machine.  Ran through the labs again... but again run into the following issues.  See below.  FYI.  I am able to ssh to my instances on AWS from my WSL Ubuntu machine, so I know that is working.  I am using the correct Region and key_pair, but getting the error below.  

**Issue1:  Locking (Solved... workaround using "-lock=false" flag**.  Is this occurring because I have the same GIT project cloned on my windows machine, with terraform init  / plan / apply performed?  I did destroy before implementing the below.  

$ terraform plan
Error: Error locking state: Error acquiring the state lock: open terraform.tfstate: permission denied

Terraform acquires a state lock to protect the state from being written
by multiple users at the same time. Please resolve the issue above and try
again. For most commands, you can disable locking with the "-lock=false"
flag, but this is not recommended.

**Issue 2:  No valid Credentials (provider.aws)**
$ terraform plan **-lock=false**
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

**Error: Error refreshing state: 1 error(s) occurred:
 provider.aws: No valid credential sources found for AWS Provider.**
        Please see https://terraform.io/docs/providers/aws/index.html for more information on
        providing credentials for the AWS Provider

**Comment by scottslowe** [comment]
@melshman The second issue, at least, can be solved by providing proper AWS credentials to Terraform. If you have the AWS CLI installed, configured, and working correctly, then Terraform will automatically pull the appropriate credentials. If not, then you'll need to supply credentials. See https://www.terraform.io/docs/providers/aws/index.html for details on supplying credentials for Terraform to use.

The first issue, on the other hand, isn't quite as clear-cut. If you've destroyed all the infrastructure, then you don't technically need to persist the state. I would first verify that the relevant AWS infrastructure has been destroyed (you can use the AWS console or the AWS CLI, but the console is probably faster/easier), then just delete all the `*.tfstate` files (as well as `*.tfstate.backup` and `*.tfstate.lock` files). This will clear out the Terraform state, which you can then recreate upon the next `terraform plan`.

I should probably update the docs to indicate that having the AWS CLI installed, configured, and working properly is a prerequisite. If you're feeling adventurous and would like to try your hand at a pull request, feel free to give that a swing.

(Note that my replies may be delayed as I'm out on vacation this week.)

**Comment by melshman** [comment]
Scott,
This can wait!  Enjoy your vacation.  I am just trying to move forward when I can.  Not rush at all.  I really appreciate the opportunity to get some instruction on this topic.

**Success followed by the initial issue.**
i installed AWS CLI and confirmed access key and secret.  that worked.  Afterwards i was able to perform the terraform plan and terraform apply and resources properly created in AWS.  
Note:  I still could not get around using '-lock=false' in both the terraform plan and terraform apply commands.   Not sure what is going on there.  but not stopping progress with work around so moved forward.

****The Issue:**  Region not supported - connection to region failed**
The issue I am at now is that I am getting the same error I started off this whole battle with back on Windows 10.  first sentence of my first post on this issue above.  
$ python ec2.py --list
**region name: None likely not supported, or AWS is down.  connection to region failed.**

I changed the ec2.ini to use 'us-east-1' instead of auto.  same error upon running, but now it says 'us-east-1'
$ sudo python ec2.py
**region name: **'us-east-1'** likely not supported, or AWS is down.  connection to region failed.m**

**Moving on... to run Ansible playbook...** 
here is what I get when I actually run the playbook, without ever having success with the ec2.py script.

e$ ansible-playbook playbook.yml
 [WARNING]:  * Failed to parse /home/melshman/projects/2018-itx-iac-workshop/ansible/ec2.py with script
**plugin: Inventory script (/home/melshman/projects/2018-itx-iac-workshop/ansible/ec2.py) had an
execution error: region name: 'us-east-1' likely not supported, or AWS is down.  connection to region
failed.**

 [WARNING]:  * Failed to parse /home/melshman/projects/2018-itx-iac-workshop/ansible/ec2.py with ini
plugin: /home/melshman/projects/2018-itx-iac-workshop/ansible/ec2.py:3: Error parsing host definition
''''': No closing quotation

 [WARNING]: Unable to parse /home/melshman/projects/2018-itx-iac-workshop/ansible/ec2.py as an
inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost
does not match 'all'


PLAY [all] *********************************************************************************************
skipping: no hosts matched
 [WARNING]: Could not match supplied host pattern, ignoring: tag_role_node


PLAY [tag_role_node] ***********************************************************************************
skipping: no hosts matched

PLAY RECAP *********************************************************************************************


END----------------------------



**here is the ansible info, although ansible is not really the issue here, it is the python script ec2.py:**
$ ansible --version
ansible 2.5.2
  config file = /home/melshman/projects/2018-itx-iac-workshop/ansible/ansible.cfg
  configured module search path = [u'/home/melshman/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/melshman/.local/lib/python2.7/site-packages/ansible
  executable location = /home/melshman/.local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

**Comment by scottslowe** [comment]
@melshman There's a couple of things you can try:

1. Try setting the AWS_REGION environment variable to the AWS region you want to use.
2. Try running `aws configure` to configure a default region for the AWS CLI.

Try one or both of these and let me know what happens.

**Comment by melshman** [comment]
Update.  By deleting the git repo on my windows 10 machine and destroying everything in AWS related to this project, I was able to get the locking issue to subside when running from my WSL machine.  

I was then able to do the following from my WSL machine successfully without '-lock=false':
terrafom init
terraform plan
terraform apply

All AWS resources were confirmed to have been created.

But when I run the $ python ec2.py --list', I still get the same error.

$ sudo python ec2.py --list
**region name: None likely not supported, or AWS is down.  connection to region failed.**

**Comment by melshman** [comment]
Thanks... good but more bad...

1. Try setting the AWS_REGION environment variable to the AWS region you
want to use.

OK... I changed from auto  to  us-east-1 in the 'ec2.ini' file?

# provide the 'regions_exclude' option. If this is set to 'auto',
AWS_REGION or
# AWS_DEFAULT_REGION environment variable will be read to determine the
region.
*regions = us-east-1*
#regions_exclude = us-gov-west-1, cn-north-1

2.  Try running aws configure to configure a default region for the AWS CLI.
$ aws configure
AWS Access Key ID [****************N3LA]:
AWS Secret Access Key [****************Ss7y]:
*Default region name [us-east-1]:*
Default output format [json]:

*It worked!  I changed the file, redeployed via terraform, ran 'sudo
phython ec2.py --list' command and got correct output.   Then i moved on to
running ansible-playbook command but that failed.  *


*Unfortunately... next issue.  - error running ansible-playbook*
When I finally run the 'sudo ansible-playbook playbook.yml' command i get:
$ sudo ansible-playbook playbook.yml
sudo: ansible-playbook: command not found

So then I run it without the sudo and get file access errors...

$ ansible-playbook playbook.yml
 [ERROR]:


PLAY [all]
******************************************************************************************************************

TASK [Install Python]
*******************************************************************************************************
fatal: [34.205.87.184]: UNREACHABLE! => {"changed": false, "msg": "Failed
to connect to the host via ssh: no such identity:
/home/melshman/.ssh/aws_rsa: No such file or directory\r\nPermission denied
(publickey).\r\n", "unreachable": true}
fatal: [54.227.197.71]: UNREACHABLE! => {"changed": false, "msg": "Failed
to connect to the host via ssh: no such identity:
/home/melshman/.ssh/aws_rsa: No such file or directory\r\nPermission denied
(publickey).\r\n", "unreachable": true}
fatal: [54.237.249.177]: UNREACHABLE! => {"changed": false, "msg": "Failed
to connect to the host via ssh: no such identity:
/home/melshman/.ssh/aws_rsa: No such file or directory\r\nPermission denied
(publickey).\r\n", "unreachable": true}
fatal: [54.172.73.95]: UNREACHABLE! => {"changed": false, "msg": "Failed to
connect to the host via ssh: no such identity: /home/melshman/.ssh/aws_rsa:
No such file or directory\r\nPermission denied (publickey).\r\n",
"unreachable": true}
fatal: [34.201.72.124]: UNREACHABLE! => {"changed": false, "msg": "Failed
to connect to the host via ssh: no such identity:
/home/melshman/.ssh/aws_rsa: No such file or directory\r\nPermission denied
(publickey).\r\n", "unreachable": true}
fatal: [54.172.83.227]: UNREACHABLE! => {"changed": false, "msg": "Failed
to connect to the host via ssh: no such identity:
/home/melshman/.ssh/aws_rsa: No such file or directory\r\nPermission denied
(publickey).\r\n", "unreachable": true}
 [WARNING]: Could not create retry file
'/home/melshman/projects/2018-itx-iac-workshop/ansible/playbook.retry'.
[Errno 13] Permission denied:
u'/home/melshman/projects/2018-itx-iac-workshop/ansible/playbook.retry'


PLAY RECAP
******************************************************************************************************************
34.201.72.124              : ok=0    changed=0    unreachable=1    failed=0
34.205.87.184              : ok=0    changed=0    unreachable=1    failed=0
54.172.73.95               : ok=0    changed=0    unreachable=1    failed=0
54.172.83.227              : ok=0    changed=0    unreachable=1    failed=0
54.227.197.71              : ok=0    changed=0    unreachable=1    failed=0
54.237.249.177             : ok=0    changed=0    unreachable=1    failed=0



Tim

**Comment by melshman** [comment]
I got it!  Ansible was looking in the wrong location for the keypair file.  changed it and got past the above.  
It all works now. 

BTW... after reviewing the playbook.yml file, i had a quick question.  

I understand that the .cfg file is using ec2.py as the inventory.  That makes sense for the task that uses hosts: "all", which affected 6 instances.  My question is what is the difference in the second portion of the playbook when it uses this:  **- hosts: tag_role_node.**  What is **tag_role_node,**, is it a keyword, and where does it determine what hosts to use?  
I navigated to the /ansible/roles/kubeadm/tasks and see where the tasks are defined for the role 'kubeadm'.  And I also see that a tag is defined.  
  **tags:
    - kubernetes**

I actually just found this... in the ec2.py -- list output:  Is this what it is looking at?   
        **"ec2_tag_Name": "k8s-2",
        "ec2_tag_role": "node",**

and also noticed that the ec2 instance that only had python installed does not have a tag name or tag role.  Mystery solved.

**Second Question:**
Why are these items with "":
  apt:
    name: "{{ item }}"
    state: "present"
  with_items:
    **- "docker.io"
    - "kubectl"
    - "kubelet"
    - "kubeadm"**

And why are these items without ""
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    **- /etc/kubernetes
    - /etc/kubernetes/audit**


Thanks for you help on this tutorial.  It feels great to have it working.

**Comment by scottslowe** [comment]
@melshman Sorry about the error with the SSH key; it occurred to me after reading your previous update that the SSH key specified in `ansible.cfg` was incorrect, but you resolved the error before I could respond here.

As for your question regarding quotes: the quotes around `{{ item }}` are required (Ansible won't parse it correctly otherwise), but quotes almost everywhere else are optional. I generally try to use them everywhere for consistency, but (as you can see) I didn't live up to that standard here.

Finally, regarding tags and such: the `ec2.py` inventory script uses AWS tags to create inventory groups (like "tag_role_node"); the tags are assigned by Terraform. This allows you to target specific subsets of your AWS EC2 inventory for certain tasks based on tag. The tags in the Ansible playbook are unrelated; they allow you to limit which tasks should be executed by instructing Ansible to only execute tasks with a particular tag.

I hope this helps!

**Comment by scottslowe** [comment]
@melshman I spawned two separate issues (#5 and #6, both addressed already) to fix the issues you brought up in this issue. I'll go ahead and close this, but feel free to re-open or create a new issue if you run into further problems or have more questions. Thanks!
